package day7;

import java.util.Random;
import java.util.Scanner;

public class NumberGuessingGame {

	public static void main(String[] args) {

		Scanner scanner = new Scanner(System.in);

		Random random = new Random();
		int targetNumber = random.nextInt(10) + 1;// generating random number 1 to 10

		int attempts = 5;
		boolean correctGuess = false;

		System.out.println("Welcome to number guessing game!");
		System.out.println("Guess number generated by computer 1 to 10");
		System.out.println("you have " + attempts + " attempts, Good luck!");

		for (int i = 1; i <= attempts; i++) {
			System.out.println("Attempt " + i + ": Enter your guess");
			int guessNumber = scanner.nextInt();

			if (guessNumber == targetNumber) {
				System.out.println("Congratulation! you win the game");
				correctGuess = true;
				break;
			} else {
				System.out.println("Wrong guess");
				if (i < attempts) {
					System.out.println("Try again please!");
				}
			}
		}
		if (!correctGuess) {
			System.out.println("You have used all attempts and correct number was: " + targetNumber);
		}
		scanner.close();

	}

}
